[workspace]
authors = ["Wm Talcott <wtalcott@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly/"]
name = "napi-mojo"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
mojo = "==0.26.3.0.dev2026031605"
